---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: mikefarah/yq
    tag: "4"

# Can't pass in an array containing the rankings repositories, have to use this hacky solution :(
inputs:
  - name: rankings-0
  - name: rankings-1

outputs:
  - name: home-config

run:
  path: sh
  # for each input repository, another yq statement needs to be added to parse that repo's values.yaml
  args:
    - -exc
    - |
      printf "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: visualizations-home-config\ndata:\n  regions: |\n" >> home-config/regions.yaml

      yq eval '.regions' rankings-0/visualizations/values.yaml | awk '{ print "    " $0 }' >> home-config/regions.yaml
      yq eval '.regions' rankings-1/visualizations/values.yaml | awk '{ print "    " $0 }' >> home-config/regions.yaml

      cat home-config/regions.yaml
