---
resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.17"
  - name: helm
    type: docker-image
    source:
      repository: typositoire/concourse-helm3-resource

resources:
  - name: data-git
    type: git
    icon: github
    source:
      # These settings should match the repositoryPath set in the deploy job
      uri: https://github.com/vbrunsch/rankings
      branch: main
      paths:
        - visualizations
  - name: app-git
    type: git
    icon: github
    source:
      uri: https://github.com/aochen-jli/visualizations
      branch: main
      ignore_paths:
        - README.md
        - .gitignore
        - examples
  - name: docker
    type: docker-image
    icon: docker
    source:
      repository: vis-docker-registry:5000/visualizations
      insecure_registries: ["vis-docker-registry:5000"]
      tag_as_latest: true
  - name: kubectl
    type: kubernetes
    icon: kubernetes
    source:
      server: https://kubernetes:443
      namespace: default
      certificate_authority: ((cluster-auth.certificate-authority-data))
      token: ((cluster-auth.token))
  - name: helm
    type: helm
    icon: ship-wheel
    source:
      cluster_url: https://kubernetes:443
      namespace: default
      helm_history_max: 5
      cluster_ca: ((cluster-auth.certificate-authority-data))
      token: ((cluster-auth.token))

jobs:
  - name: build-image
    serial: true
    plan:
      - get: app-git
        trigger: true
      - put: prune-system
        resource: kubectl
        params:
          kubectl: >
            apply -f https://raw.githubusercontent.com/aochen-jli/visualizations-cicd/main/pipelines/jobs/prune-host-docker-system.job.yaml
          wait_until_ready: 600
      - put: prune-registry
        resource: kubectl
        params:
          kubectl: >
            exec -it $(kubectl get pods -l app=docker-registry -o custom-columns=:metadata.name)
            --
            /bin/registry garbage-collect /etc/docker/registry/config.yml --delete-untagged
          wait_until_ready: 600
      - put: docker
        params:
          build: app-git
        get_params: {skip_download: true}

  - name: deploy
    serial: true
    plan:
      - get: app-git
        passed: [build-image]
        trigger: true
      - get: data-git
        trigger: true
      - put: upgrade-deployments
        resource: helm
        params:
          chart: app-git/helm/chart/
          values:
            - app-git/helm/chart/values.yaml
            - data-git/visualizations/values.yaml  # The repository-specific values should override the defaults
          override_values:
            - key: repositoryPath  # Should match the configuration for the data-git resource
              value: https://raw.githubusercontent.com/vbrunsch/rankings/main/visualizations
              type: string
          release: visualizations
      - put: restart-deployments
        resource: kubectl
        params:
          kubectl: >
            rollout restart deployment
            $(kubectl get deployment -l app.kubernetes.io/name=visualizations -o custom-columns=:metadata.name)
          wait_until_ready: 600
