---
resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.17"
  - name: helm
    type: docker-image
    source:
      repository: typositoire/concourse-helm3-resource

resources:
  - name: rankings-intl
    type: git
    icon: github
    source:
      # These settings should match the repositoryPath set in the deploy job
      uri: https://github.com/vbrunsch/rankings
      branch: main
      paths:
        - visualizations
  - name: vis-app
    type: git
    icon: github
    source:
      uri: https://github.com/aochen-jli/visualizations
      branch: main
      ignore_paths:
        - README.md
        - .gitignore
        - examples
  - name: tasks
    type: git
    icon: github
    source:
      uri: https://github.com/aochen-jli/visualizations-cicd
      branch: main
  - name: docker
    type: docker-image
    icon: docker
    source:
      repository: registry.nocovid.group/visualizations
      username: ((regcred.docker-username))
      password: ((regcred.docker-password))
      tag_as_latest: true
  - name: kubectl
    type: kubernetes
    icon: kubernetes
    source:
      server: https://kubernetes:443
      namespace: default
      certificate_authority: ((cluster-auth.certificate-authority-data))
      token: ((cluster-auth.token))
  - name: helm
    type: helm
    icon: ship-wheel
    source:
      cluster_url: https://kubernetes:443
      namespace: default
      helm_history_max: 5
      cluster_ca: ((cluster-auth.certificate-authority-data))
      token: ((cluster-auth.token))

jobs:
  - name: build
    serial: true
    plan:
      - get: vis-app
        trigger: true
      - get: tasks
      - task: prune-images
        file: tasks/pipelines/tasks/prune-images.task.yaml
      - put: docker
        params:
          build: vis-app
        get_params: {skip_download: true}

  - name: deploy
    serial: true
    plan:
      - get: vis-app
        passed: [build]
        trigger: true
      - get: rankings-intl
        trigger: true
      - put: upgrade-deployments
        resource: helm
        params:
          chart: vis-app/helm/chart/
          values:
            - vis-app/helm/chart/values.yaml
            - rankings-intl/visualizations/values.yaml  # The needs to point to the repository-specific values.yaml file
          override_values:
            - key: repositoryPath  # Should match the configuration for the rankings-intl resource
              value: https://raw.githubusercontent.com/vbrunsch/rankings/main/visualizations
              type: string
          release: visualizations-intl  # Use a unique release name
      - put: restart-deployments
        resource: kubectl
        params:
          # Ensure the release name specified for visualizations/release matches the release specified above
          kubectl: >
            rollout restart deployment
            $(kubectl get deployment -l visualizations/release=visualizations-intl -o custom-columns=:metadata.name)
          wait_until_ready: 600
