---
resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.17"

resources:
  - name: rankings-intl
    type: git
    icon: github
    source:
      uri: https://github.com/vbrunsch/rankings
      branch: main
      paths:
        - visualizations/values.yaml
  - name: rankings-usa
    type: git
    icon: github
    source:
      uri: https://github.com/jsn-li/County_Ranking
      branch: master
      paths:
        - visualizations/values.yaml
  - name: home-app
    type: git
    icon: github
    source:
      uri: https://github.com/jsn-li/visualizations-home
      branch: main
      ignore_paths:
        - README.md
        - .gitignore
  - name: tasks
    type: git
    icon: github
    source:
      uri: https://github.com/jsn-li/visualizations-cicd
      branch: main
  - name: docker
    type: docker-image
    icon: docker
    source:
      repository: registry.nocovid.group/visualizations-home
      username: ((regcred.docker-username))
      password: ((regcred.docker-password))
      tag_as_latest: true
  - name: kubectl
    type: kubernetes
    icon: kubernetes
    source:
      server: https://kubernetes:443
      namespace: default
      certificate_authority: ((cluster-auth.certificate-authority-data))
      token: ((cluster-auth.token))

jobs:
  - name: build
    serial: true
    plan:
      - get: home-app
        trigger: true
      - get: tasks
      - task: prune-images
        file: tasks/pipelines/tasks/prune-images.task.yaml
      - put: docker
        params:
          build: home-app
        get_params: {skip_download: true}

  - name: deploy
    serial: true
    plan:
      - get: home-app
        passed: [build]
        trigger: true
      - get: rankings-intl
        trigger: true
      - get: rankings-usa
        trigger: true
      - get: tasks
      - task: make-home-config
        file: tasks/pipelines/tasks/make-home-config.task.yaml
        input_mapping:
          rankings-0: rankings-intl
          rankings-1: rankings-usa
        output_mapping:
          home-config: home-config
      - task: ensure-config-endpoints
        file: tasks/pipelines/tasks/ensure-config-endpoints.task.yaml
        params:
          TIMEOUT: 1200
        input_mapping:
          home-config: home-config
      - put: apply-home-config
        resource: kubectl
        params:
          kubectl: apply -f home-config/
          wait_until_ready: 0
      - put: upgrade-deployment
        resource: kubectl
        params:
          kubectl: apply -f home-app/ci/
          wait_until_ready: 600
      - put: restart-deployment
        resource: kubectl
        params:
          kubectl: rollout restart -f home-app/ci/visualizations-home.deployment.yaml
          wait_until_ready: 600
