---
resources:
  - name: pipelines
    type: git
    icon: github
    source:
      uri: https://github.com/jsn-li/visualizations-cicd
      branch: main
      paths:
        - pipelines

jobs:
  - name: set-self
    serial: true
    plan:
      - get: pipelines
        trigger: true
      - set_pipeline: set-pipelines
        file: pipelines/pipelines/set-pipelines.pipeline.yaml
  - name: set-others
    serial: true
    plan:
      - get: pipelines
        passed: [set-self]
        trigger: true
      - set_pipeline: deploy-vis
        file: pipelines/pipelines/deploy-vis.pipeline.yaml
      - set_pipeline: deploy-home
        file: pipelines/pipelines/deploy-home.pipeline.yaml
