---
resources:
  - name: git
    type: git
    icon: github
    source:
      uri: https://github.com/aochen-jli/rankings-cicd

jobs:
  - name: set-self
    plan:
      - get: git
        trigger: true
      - set_pipeline: set-pipelines
        file: git/pipelines/set-pipelines.pipeline.yaml
  - name: set-others
    plan:
      - get: git
        passed: [set-self]
        trigger: true
      - set_pipeline: build-and-deploy
        file: git/pipelines/build-and-deploy.pipeline.yaml
