---
resources:
  - name: pipelines-git
    type: git
    icon: github
    source:
      uri: https://github.com/aochen-jli/visualizations-cicd
      branch: main
      paths:
        - pipelines

jobs:
  - name: set-self
    serial: true
    plan:
      - get: pipelines-git
        trigger: true
      - set_pipeline: set-pipelines
        file: pipelines-git/pipelines/set-pipelines.pipeline.yaml
  - name: set-others
    serial: true
    plan:
      - get: pipelines-git
        passed: [set-self]
        trigger: true
      - set_pipeline: deploy-vis
        file: pipelines-git/pipelines/deploy-vis.pipeline.yaml
      - set_pipeline: deploy-home
        file: pipelines-git/pipelines/deploy-home.pipeline.yaml
